# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='inventory.Building'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.Apartment'),
        ),
        migrations.AlterUniqueTogether(
            name='apartment',
            unique_together=set([('building', 'number')]),
        ),
    ]
